version: 2

project_name: akme

before:
  hooks:
    - go mod tidy

builds:
  - id: akme
    main: ./cmd/akme
    binary: akme
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w -X main.version={{ .Version }} -X main.commit={{ .Commit }} -X main.date={{ .Date }}

archives:
  - id: akme
    ids:
      - akme
    formats:
      - tar.gz
    name_template: >-
      {{ .ProjectName }}_{{ .Os }}_{{ .Arch }}
    files:
      - README.md

checksum:
  name_template: checksums.txt

release:
  github:
    owner: o1x3
    name: akme
