name: ci

on:
  push:
    branches: [main]
  pull_request:

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7.0.1

      - uses: actions/setup-go@v7.0.0
        with:
          go-version-file: go.mod
          cache: true

      - uses: actions/setup-node@v7.0.0
        with:
          node-version: "22"

      - name: Check
        run: scripts/check.sh
